// Generated by CoffeeScript 1.8.0
(function() {
  var clean, concat, flatten, gif, gulp, path, paths, plumber, sass, sourcemaps, watch;

  gulp = require('gulp');

  watch = require('gulp-watch');

  clean = require('gulp-clean');

  concat = require('gulp-concat');

  sass = require('gulp-sass');

  sourcemaps = require('gulp-sourcemaps');

  path = require('path');

  gif = require('gulp-if');

  flatten = require('gulp-flatten');

  plumber = require('gulp-plumber');

  paths = {
    "public": 'static/assets/js',
    scripts: ['static/assets/js/modernizr.custom.61112.js', 'static/assets/js/jquery-1.8.2.min.js', 'static/assets/js/jquery.address-1.6.js', 'static/assets/vendor/sco.js/js/sco.ajax.js', 'static/assets/vendor/sco.js/js/sco.panes.js', 'static/assets/vendor/sco.js/js/sco.tab.js', 'static/assets/js/ddsmoothmenu-min.js', 'static/assets/js/jquery.dcjqaccordion.2.7.min.js', 'static/assets/js/jquery.easytabs.min.js', 'static/assets/js/slide-to-top-accordion-min.js', 'static/assets/js/jquery.easing-1.3.min.js', 'static/assets/js/jquery.flexslider-min.js', 'static/assets/js/responsive-tables.js', 'static/assets/vendor/SlitSlider/js/jquery.ba-cond.min.js', 'static/assets/vendor/SlitSlider/js/jquery.slitslider.js', 'static/assets/js/bootstrap.min.js', 'static/assets/js/scripts.js'],
    styles: []
  };

  gulp.task("scripts", function() {
    return gulp.src(paths.scripts).pipe(sourcemaps.init()).pipe(concat("all.js")).pipe(sourcemaps.write()).pipe(gulp.dest(paths["public"]));
  });

  gulp.task("default", ['scripts']);

}).call(this);

//# sourceMappingURL=Gulpfile.js.map
